### ISSUE TITLE
Hidden Zones

### ISSUE THREAD

**Issue by teliot** [LostSavage/SecretHitlerCE#12]
When using shuffle players. The zone you were sitting at before the shuffle is transparent, the zone you random too is not transparent.

**Comment by LostSavage** [comment]
This is a bug in TTS a rewind will fix it.

**Comment by teliot** [comment]
On item #12 i teliot will give a second evaluation and investigation to confirm said cause of tts bug of transparency of player zones with shuffle players selected with either the host selected or the shuffle host not selected which is a new issue not present until the recent covid 19 crises which was originally considered to be the cause of transparency issue of player zones after shuffle colors were selected with either the shuffle host selected or the shuffle host not selected effecting the following colors white red orange yellow green blue purple pink teal brown
